version: '2'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3-management
    ports:

      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - 'rabbitmq_data:/Users/joeylam/dev/rabbitmq'
volumes:
  rabbitmq_data:
    driver: local