version: '3.8'
services:
  rabbitmq:
    container_name: "myrabbit"
    image: rabbitmq:3-management
    ports:
      - '5672:5672'     # AMQP protocol port
      - '15672:15672'   # HTTP management UI
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - 'rabbitmq_data:/Users/joeylam/dev/rabbitmq'
volumes:
  rabbitmq_data:
    driver: local